### ISSUE TITLE
EPIC_Gene_3_200_new.rds file has chr positions with the start bigger than end

### ISSUE THREAD

**Issue by tiagochst** [TransBioInfoLab/coMethDMR_data#1]
The file EPIC_Gene_3_200_new has  positions with the start bigger than end. See code below:

```r
probes.cluster.all <- readRDS("~/TBL Dropbox/Tiago Silva/AD-meta-analysis-blood-samples-bySex/datasets/coMethDMR_data-main/data/EPIC_Gene_3_200_new.rds")
names(probes.cluster.all)[6]
```

<img width="223" alt="Screen Shot 2022-01-31 at 1 48 51 PM" src="https://user-images.githubusercontent.com/145529/151854230-6455c65d-38fd-4493-ad5a-f21c35b2ab37.png">

**Comment by gabrielodom** [comment]
I'm updating `coMethDMR::` to use `IlluminaHumanMethylationEPICanno.ilm10b4.hg19::`. Hopefully this solves our problem.
See <https://github.com/TransBioInfoLab/coMethDMR/issues/14>.

**Comment by gabrielodom** [comment]
@tiagochst, please check the new results. I see the following:
```
> allClusters_min3_200bp_ls[6]
$`chr10:52611821-52612019`
[1] "cg04167299" "cg24726946" "cg10222734"
```

There is a new data file called `data/EPIC_10b4_Gene_3_200.rds`.

**Comment by tiagochst** [comment]
@gabrielodom  There are a lot of NAs in the names
<img width="858" alt="Screen Shot 2022-02-23 at 9 18 12 AM" src="https://user-images.githubusercontent.com/145529/155337205-521f2a8d-5100-4514-a2bc-93602c41b259.png">

**Comment by gabrielodom** [comment]
Crap. That was my test version; I only named the first 5. I really thought I had committed the real one. Give me a sec

**Comment by gabrielodom** [comment]
Actually, give me an hour. It takes about 58 minutes to rebuild that data set.

**Comment by gabrielodom** [comment]
@tiagochst, can you try now?

**Comment by tiagochst** [comment]
Now it looks good!
